apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-demo
  namespace: gin-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-demo
  template:
    metadata:
      labels:
        app: gin-demo
    spec:
      containers:
        - image: 843665303/gin-demo:v1.0
          name: gin-demo-containers
          ports:
            - containerPort: 9090