apiVersion: v1
kind: Service
metadata:  #定义service的名字
  name: gin-demo-service
  namespace: gin-demo
  labels:
    name: gin-demo-service  
spec:
  type: NodePort
  ports:
    - name: gin-demo-api
      port: 9090 #这里的端口,对应的镜像访问供内部访问
      targetPort: 9090  #对应的是deployment暴露出来的端口,端口一定要和container暴露出来的端口对应
      protocol: TCP
      nodePort: 30001 # 所有的节点都会开放此端口，此端口供外部调用。
  selector:
    app: gin-demo #这里选择器一定要选择容器的标签