apiVersion: v1
kind: Service
metadata:
  name: gin-demo-service
  namespace: gin-demo
  labels:
    k8s-app:    
spec:
  type: NodePort
  ports:
    - name: gin-demo-api
      port: 9090
      targetPort: 9090
      nodePort: 30001
  selector:
    app.kubernetes.io/name: gin-demo